services:
  application: 
    build: ex3
    ports:
      - "8080:8080"
    environment:
      - APP_DB=mysql
    restart: unless-stopped
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_PASSWORD=secret2
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
    ports:
      - 33050:3306/tcp
    restart: unless-stopped

    
